### ISSUE TITLE
How to actually turn off a PV camera?

### ISSUE THREAD

**Issue by Jing-Fu** [jdibenes/hl2da#19]
I disabled the PV camera through the following code, but I found that the camera light of the Hololens2 device still glowed.

        hl2da_user.SetEnable(hl2da_api.SENSOR_ID.PV, false);

**Comment by jdibenes** [comment]
Hello,
I tested it again and that code does stop the PV camera.
I found that the camera light stays on after the PV stream is disabled if the Long Throw depth stream is enabled.
It seems to be a HoloLens/Research Mode quirk but it does not affect data capture.

**Comment by Jing-Fu** [comment]
Thank you for your help. Indeed, I also turned on the depth camera for testing.
